Custom Bottom Modal
Team-WeHere/WeHere pull request #24
Opened 2022-11-21 13:47 UTC by chaneeii

## Background 

- close #4

## Description
- TabView를 이용하여 스크롤이 가능한 Bottom 모달을 구현해보았습니다..!
- MultipleStrokeHeartView 를 추가해서 여러개의 Stroke 가 있는 하트뷰를 만들었습니다

## Test Points

- ContentView 에 테스트 가능한 View를 구현해두었습니다.
- MockData 를 수정해서 테스트가 가능합니다.

```swift
struct BottomModal: View {
    @State private var currentIndex = 0
    let place = Place.mockData[1] // 0,1,2 중에 하나 골라보세요~
    
    var body: some View {
```

## Extra Notes

- Place에 `isPoked` (찌른장소인지체크) 라는 변수를 추가했습니다

## References

<p>
<img width="250" src="https://user-images.githubusercontent.com/63157395/203069991-85825d18-4f4c-4b78-8d17-5b82e5920cd9.png">
<img width="250" src="https://user-images.githubusercontent.com/63157395/203069997-a4e79767-054b-46bf-9ddc-3b54e4c65d2b.png">
<img width="250" src="https://user-images.githubusercontent.com/63157395/203069988-52abee8d-5fc3-4f4c-bb37-73300571239c.png">
</p>

https://user-images.githubusercontent.com/63157395/203070044-74f71d34-c23a-439f-abb9-86f76ded6733.mp4

2022-11-21 16:37 UTC, phainestha1 commented
UI상 애니메이션이 있는 관계로 리뷰어에 로미를 추가할게요.
탭뷰를 통해 화면을 전환하는 부분에서 상의되어야 할 부분이 있을 것 같아요.
예컨대 모달은 가만히 있고 내부의 페이지만 변경할 수 있을까요? 아래의 스샷과 같은 부분은 좀 더 괜찮은 방법이 있을 것 같아요.

<img width="550" alt="스크린샷 2022-11-22 오전 1 35 14" src="https://user-images.githubusercontent.com/88080251/203110214-5292dfd9-f61b-45e7-a51d-8ab313cf8252.png">

@mxnxxii 확인 부탁해요.

2022-11-21 18:40 UTC, mxnxxii commented
> 

저도 화면 전환시, 내부 컨텐츠만 이동하는게 깔끔할 것 같아요!
테오가 올려주신 캡쳐본을 보면 페이지네이션 부분이 모달 내부에 들어가있지 않아서 화면 전환될 때 이것만 제자리에 남아있는것도 좀 어색한 것 같네요 T.T

2022-11-22 01:55 UTC, chaneeii commented
> 

<img width="248" alt="스크린샷 2022-11-22 오전 10 54 52" src="https://user-images.githubusercontent.com/63157395/203197876-a381d04d-69e7-4952-8f54-92eeb1ea4b70.png">

이부분 바꾸려면 공수가 꽤나 있을것같아서
이 부분 협의해주시고 알려주시면 작업여부 결정하도록 하겠습니다!

@phainestha1 @mxnxxii

2022-11-22 02:47 UTC, phainestha1 commented
@chaneeii @mxnxxii 

오우 동시에 여러 논의가 진행되다보니 불필요한 작업을 할 수도 있었겠네요.
적절한 타이밍에 잘 지적해주신 것 같아요..!

메신저와 피그마 코멘트 상으로 논의된 내용에 따라서
준비중입니다 페이지는 제외하는 것으로 부탁드립니다.

주석 처리를 하셔도 좋고, 코드를 지우셔도 되겠습니다...👀👀👀👀

2022-11-22 11:20 UTC, E-know requested changes
고생하셨습니다!

2022-11-22 11:20 UTC, E-know commented on WeHere/Assets.xcassets/pin/notyet.imageset/Contents.json
> +}
[P1] PDF나 벡터 포맷터로 추출 후에 원사이즈가 좋지 않을까 생각됩니다!

2022-11-22 11:20 UTC, E-know commented on WeHere/Views&ViewModels/Components/HeartView/MultipleStrokeHeartView.swift
> +    var image = "sample-profile"
[P3] 외부에서 사용하지 않는다면 private이 좋지 않을까 생각됩니다.

2022-11-22 11:20 UTC, E-know commented on WeHere/Views&ViewModels/Components/Modal/BottomModal/BottomModal.swift
> +                            .padding(EdgeInsets(top: 28, leading: 28, bottom: 28, trailing: 28))
```suggestion
                            .padding(28)
```
[P1] 4방위가 28로 동일하다면 위와 같이 줘도 좋을 것 같습니다.

2022-11-22 11:20 UTC, E-know commented on WeHere/Views&ViewModels/Components/Modal/BottomModal/BottomModal.swift
> +                            .padding(EdgeInsets(top: 28, leading: 28, bottom: 28, trailing: 28))
[P1] 이 역시 마찬가지 입니다.

2022-11-22 11:20 UTC, E-know commented on WeHere/Views&ViewModels/Components/Modal/BottomModal/BottomModal.swift
> +            .padding(.all, 10)
```suggestion
            .padding(10)
```
[P4] 이 부분에서 방향을 지정하신 이유가 있으실까요??

2022-11-22 11:20 UTC, E-know commented on WeHere/Views&ViewModels/Components/Modal/BottomModal/BottomModal.swift
> +    }
```suggestion
private var pokeView: some View {
        VStack {
            HStack {
                Text(place.name)
                    .font(Font.theme.title1)
                Spacer()
            }
            HStack {
                Image(place.category.name)
                    .resizable()
                    .frame(width: 20, height: 24)
                Text(place.address)
                    .font(Font.theme.body2)
                    .foregroundColor(Color.gray02)
                Spacer()
            }
            
            Button {
                HapticManager.shared.notification(type: .success)
            } label: {
                MultipleStrokeHeartView(width: 112, height: 105, isPoked: place.isPoked, image: "profile-girl")
            }
            .padding(.bottom, 25)
            
            Text(place.isPoked
                 ? "푸린님이 콕 한 장소에요!"
                 : "폼폼님께 이 장소를 콕 하세요!")
            .font(Font.theme.body2)
            .foregroundColor(Color.gray02)
        }
    }
```
[P1] 하나의 뷰에 필요 이상의 객체를 너무 많이 들고 있다는 생각입니다. 위와 같이 제안합니다. 
더 줄일수 있다면 Best `placeDetailView`도 역시 필요이상의 너무 많은 객체가 있다는 생각 입니다.

2022-11-22 11:24 UTC, chaneeii commented on WeHere/Assets.xcassets/pin/notyet.imageset/Contents.json
> +}
저도 처음에 그렇게 했는데, 요파일이 테오가 임시로 만든 파일이라 그런지 추출했을때 svg가 깨지더라구요! 
아마 요 어셋은 제거될 예정이라 임시로 요렇게 처리해두었습니다!

2022-11-22 11:28 UTC, chaneeii commented on WeHere/Views&ViewModels/Components/HeartView/MultipleStrokeHeartView.swift
> +    var image = "sample-profile"
외부에서 변수로 받아서 사용한답니당..!
하지만 너무 막 만들어서 재사용성 고려해서 다시 만들어둘게요

2022-11-22 11:30 UTC, chaneeii commented on WeHere/Views&ViewModels/Components/Modal/BottomModal/BottomModal.swift
> +                            .padding(EdgeInsets(top: 28, leading: 28, bottom: 28, trailing: 28))
바꾸는걸 까먹었네요! 감사합니다
8d5a909ff75a88ebedba1ff0a99237f79aebb42b

2022-11-22 11:30 UTC, chaneeii commented on WeHere/Views&ViewModels/Components/Modal/BottomModal/BottomModal.swift
> +                            .padding(EdgeInsets(top: 28, leading: 28, bottom: 28, trailing: 28))
바꾸는걸 까먹었네요! 감사합니다
8d5a909ff75a88ebedba1ff0a99237f79aebb42b

2022-11-22 11:34 UTC, chaneeii commented on WeHere/Views&ViewModels/Components/Modal/BottomModal/BottomModal.swift
> +    }
오 이게 되네요 좋은 지적 감사합니다..!
스유 뷰 그릴때 한번 더 고려해보겠습니다
e143cbfdf17d743f90729a2aa1076da82308f612

2022-11-22 11:38 UTC, chaneeii commented on WeHere/Views&ViewModels/Components/HeartView/MultipleStrokeHeartView.swift
> +    var image = "sample-profile"
private 으로 처리하고 init 으로 받는 방식으로 변경했습니다~
ee9c4d761ba6fd0d966e4279d320731de5dab01d

2022-11-22 11:45 UTC, chaneeii commented
> @chaneeii @mxnxxii
> 
> 오우 동시에 여러 논의가 진행되다보니 불필요한 작업을 할 수도 있었겠네요. 적절한 타이밍에 잘 지적해주신 것 같아요..!
> 
> 메신저와 피그마 코멘트 상으로 논의된 내용에 따라서 준비중입니다 페이지는 제외하는 것으로 부탁드립니다.
> 
> 주석 처리를 하셔도 좋고, 코드를 지우셔도 되겠습니다...👀👀👀👀

나중에 들어갈수도 있을 것 같아서 주석처리해두었습니다!
983c0d716b7ed0578d5fba016cbaca47d8e53a5e

2022-11-23 09:39 UTC, E-know approved these changes

2022-11-23 09:41 UTC, E-know commented
[![LGTM](https://lgtm.lol/p/9)](https://lgtm.lol/i/9)

2022-11-23 09:41 UTC, merged