Map basic UI
Team-WeHere/WeHere pull request #3
Opened 2022-11-05 16:15 UTC by chaneeii

## Background 

- close #2

## Description
 

-  Map 추가
-  MapMarker 추가
-  MapMarker 관련 이미지 및 컬러 Asset 추가
-  PlaceInfo Model 및 MockData 추가
-  Heart Fab Button 및 애니메이션

### Extension 및 공용컴포넌트 사용법
1. Color+ Extension 을 추가했습니다.
어셋을 하나하나 넣기 귀찮아서 코드로 했는데, 혹시 asset을 선호하시면 바꿀게요!
사용법은 컬러가 필요할때

```swift
.yellow02 //  방법1
Color.yellow02 // 방법2
```

2. Heart 
하트를 한땀한땀 깍았습니다.
2-1. Heart Shape 이 필요한 경우 (Shape)
```
// 이렇게나
HeartShape() .stroke(gradient, lineWidth: hasStroke ? 5 : 0)

//이렇게 
.clipShape(HeartShape())

```
2-2. HeartView 사용 ✨
<img width="469" alt="스크린샷 2022-11-06 오전 1 13 50" src="https://user-images.githubusercontent.com/63157395/200129436-17f723da-f18d-435f-a792-810e07c8d8ae.png">

3. Pin 
깍는김에 Pin도 한땀한땀 깍아보았는데요
사용법은 하트와 동일합니다 

## Test Points

✨ 디바이스의 현재 위치가 잘 뜨는지 확인하면 좋을 것 같아요! (+권한)
시뮬레이터 이용시
<img width="300" alt="스크린샷 2022-11-06 오전 1 06 26" src="https://user-images.githubusercontent.com/63157395/200129135-40c4d64b-37de-456e-9714-36d721407e48.png">

✨ Pin 디자인 테스트 
주석을 해제하여  두가지 Pin 비교 부탁드립니다 🙏  (아래, `✅ Pin UI 방식에 대한 논의` 참고)
<img width="300" alt="스크린샷 2022-11-06 오전 1 03 29" src="https://user-images.githubusercontent.com/63157395/200128987-20b02dd6-98ca-442e-ab2c-55d9eb67b277.png">

## Extra Notes

✅ Pin UI 방식에 대한 논의!
Pin 을 `이미지` 로 할지 `직접만든 Shape`으로 할지 결정이 필요할 것 같습니다. (( @phainestha1 도 봐주세요 ))
혹시 몰라서 둘다 만들어두었습니다만 직접 만든 모양은 재사용성이 높지만 아무래도 약간은 피그마와 차이가 있네요

✅ Haptic 추가 여부 결정
요부분은 @mxnxxii , @phainestha1 의 의견도 필요할것같은데, 
하트 프로필을 눌렀을때 그냥 누르고 애니메이션이 뜨니 심심해서
동그라미 도트 컴포넌트들이 나올때 맞춰서 햅틱을 추가해두었는데 
이부분이 괜찮은지 확인 부탁드립니다! 별로면 바로 뺄께요!

✅ Components 
공통으로 사용하는 컴포넌트가 있어 이부분을 우선 Views&ViewModels 쪽에 넣어두었는데 
폴더위치가 애매하네요 🥹 한단계 위로 올릴까요?

✅ 카테고리
지난번에 카테고리를 서버쪽에 두어서 자유롭게 카테고리 변경이 가능하도록 하기로 논의를 했던것 같아서
현재는 임시로 카테고리를 mockdata화 시켜서 작업해두었습니다.

✅  그외
- 네트워크통신 관련 코드가 Manager 쪽에 있다고 생각하면 될까요?
  - 현재 Haptic 관련되어서 클래스를 하나 HapticManager로 파두었는데 요게 아니면 util 로 따로 폴더를 만들어 이전해야할까요?
- 알수없는 보라 경고
요 에러를 해결하고 싶은데 왜 뜨는지 잘 모르겠네요 🥲
혹시 이것에 대해서 아는게 있을까요? @E-know 
<img width="382" alt="스크린샷 2022-11-06 오전 12 51 39" src="https://user-images.githubusercontent.com/63157395/200128481-4a88266a-7d50-4824-a943-2f5962175b4e.png">
- 그리고 클로저 길이 제한 린트를 날렸습니다...! (스유에서는 너무 척박한 린트라 ,, 제맘대로하나,,,,,,ㅠㅠ)

## References

### Screenshots

영상은 용량을 챙기다보니 화질이 안좋네요ㅠ

### 현재위치 + 핀 데모
https://user-images.githubusercontent.com/63157395/200128393-b1971e8b-4187-4dc9-bdda-7ca6a1e411d7.mov

### 하트 버튼 움직이는거 데모
https://user-images.githubusercontent.com/63157395/200128401-2ba155fd-1c06-414a-915c-b067e15414b4.mov

## 💬
첫 공동작업에 첫 PR 이라 내용이 이래저래 길어졌네요..! 🥹
궁금한점있으면 알려주세요!

2022-11-05 20:06 UTC, phainestha1 commented on WeHere/Views&ViewModels/Components/Pin/PinView.swift
> +struct PinView: View {
<div>
<img src="https://user-images.githubusercontent.com/88080251/200138837-659958b4-8895-49a1-9556-b90e56a95631.jpg" alt="image" width="250"/>
<img src="https://user-images.githubusercontent.com/88080251/200138859-f36bcd8a-2ab3-4e48-95df-1a0b623e3e0a.jpg" alt="image" width="250"/>
</div>

좌측이 커스텀, 우측이 이미지인데 제 기기 상으로 이미지로 구현된 핀은 사이즈가 더 크네요.
@mxnxxii 의 의견으로 진행하고자 합니다.
저는 상대적으로 작게 표시되는 것이 보기 편하네요.

2022-11-06 04:30 UTC, chaneeii commented on WeHere/Views&ViewModels/Map/MapView.swift
> +                                HapticManager.instance.notification(type: .success)
오오오 좋은 의견 감사합니다!
제가 너무 심심해서 잔재주를 부린거라 `반영이 안되어도 이러면 쫌 재밌네` 하고 추가한 햅틱피드백입니다 
저는 다음과 같은 생각들을하다가 추가를 해보게 되었습니다. (다소 개발적 이야기도 담긴)

> 몬가 쓰다보니 구구절절 길게 써보았는데 이고민 블로그에 써야겠네요 
> 꽤나 UX 적으로 재미있는 고민이여서 공유해봐요!

PR 에 이유를 쓰다가 너무 길어져서 Discussion 을 파서 올려봅니다!

- https://github.com/Team-WeHere/WeHere/discussions/5

햅틱매니저를 만들어서 아무때나 재사용이 가능하니 햅틱이 필요하다면 필요한 순간을 적절히 잘 설계해주시면 바로 반영가능이요 ✨

2022-11-06 04:37 UTC, chaneeii commented on WeHere/Views&ViewModels/Components/Pin/PinView.swift
> +struct PinView: View {
이미지로 구현된 부분도 사이즈를 조절하려면 조절할수있습니다! 다만 이미지로 한 부분은 동적으로 애플이 기본제공해주는 parentview 에 맞추려고 따로 높이 넓이를 설정해주지 않아 저렇게 나오게 되었습니다.

커스텀은 제가 너무 큰것같아보여서 임의로 사이즈를 일반적인 핀 사이즈로 줄여둔 부분입니다.

둘다 사이즈는 조절가능해요

2022-11-06 06:13 UTC, phainestha1 commented on WeHere/Views&ViewModels/Map/MapView.swift
> +                                HapticManager.instance.notification(type: .success)
써주신 글 상세하게 읽어보았습니다. 버튼 하나에도 많은 고민을 하셨네요.
@mxnxxii 로미와 저에게 최종 결정권을 주셨으니 먼저 제 쪽에서 다음과 같이 제안드리고 싶습니다.
로미 확인 후 본 코멘트 종료할 수 있도록 할게요.

1. 하트 버튼의 애니메이션 여부
Discussion 본문 예시의 깜빡거림 애니메이션은 다음과 같은 우려 사항이 있었습니다. 

- highlight 상태일 때 버튼이 투명해지면서, 뒤에 가려져 있던 카테고리들이 노출
- 화면에서 사라지는 듯한 이질감

그렇다면 투명해지는 방식이 아닌 버튼의 밝기를 조절하는 방식을 적용하는 것은 어떨까요? 아래의 예시를 확인 부탁드립니다.

https://user-images.githubusercontent.com/88080251/200156576-5c1f7722-b08c-4e0b-97b1-d16553c17d65.mp4

```swift
Button {
  self.showFabAnimation.toggle()
} label: {
  HeartView()
    .frame(width: 92, height: 92)
}
  .buttonStyle(SampleButtonStyle())

// Sample Button Style
struct SampleButtonStyle: ButtonStyle {
  func makeBody(configuration: Self.Configuration) -> some View {
    configuration.label
      .brightness(configuration.isPressed ? -0.15 : 0)
      .background(.clear)
  }
}
```

코드는 안이쁘네요..

2. 햅틱을 통한 재미 요소
이 부분은 깊이 공감합니다. 
콕 기능을 진행하기 전에 메인 화면에서 사용자에게 재미 요소를 전달하면 좋은 인상을 남길 수 있을 것 같아요.

생각해보고 싶은 부분은 버튼을 터치한 후 햅틱이 발생하는 0.48초 간의 타이밍 차이입니다.
저는 버튼을 터치한 후 그에 따른 리액션이 즉각적으로 표시되어야 한다고 생각했습니다. 때문에 0.5초 가량의 딜레이는 꽤 긴 시간이라는 느낌이 들었어요. 

실기기 테스트 당시 버튼을 터치했을 때 바로 반응이 오지 않아서 3~4번 정도 연타를 했고, 때문에 카테고리들이 나오다가 다시 들어가는 애니메이션을 보게 되었습니다.

다만 이 의견은 본문에 기재해주신 "버튼을 누르자마자 나오면 약간 자연스럽지 못함 + 경박함이 느껴져서 약간 딜레이를 주었는데" 라는 내용과 완전히 상충되더군요.. 충분히 고민하신 내용인 만큼 그만한 이유가 있었을 것이라는 생각이 듭니다.

좀 더 디테일한 내용을 공유해주실 수 있을까요? 
해당 내용이 이해가 된다면 저도 최대한 하트 버튼에 햅틱을 추가하는 것으로 논의를 진행하겠습니다.

2022-11-06 06:33 UTC, phainestha1 commented on WeHere/Views&ViewModels/Components/Pin/PinView.swift
> +struct PinView: View {
그렇다면 저는 재사용성을 높이는 방향이 좋아보입니다.
피그마와 그렇게 크리티컬한 차이를 보이지도 않는 것 같구요.
로미를 설득해보겠습니다.

2022-11-06 07:03 UTC, mxnxxii commented on WeHere/Views&ViewModels/Map/MapView.swift
> +                                HapticManager.instance.notification(type: .success)
실기기에서 테스트해본 결과, 햅틱의 경우 눌렀을때 바로 반응이 오지 않아서 유저에게 혼동을 줄 수 있겠다는 생각이 들었어요!
햅틱을 줌으로써 재미요소를 제공한다는 것은 좋지만, 액션이 바로 발생하지 않는다는 점에서는 불편한 유저 경험이 될 수 있을 것 같네요 ㅠㅠㅠㅠㅠ

햅틱 말고 다른 대안으로 나온것이 탭을 했을 때 1. 깜박이기 / 2. 버튼의 밝기 조절인 것 같아요!

저의 의견은, 두가지 방법보다는 '하트의 크기를 크게 만들었다가 다시 원래 크기로 오는 식'으로 해보는건 어떨까 싶어요 !!
탭을 했을 때, 그 버튼이 커짐으로써 바로 반응이 온다는 것을 알 수 있으면서도 카테고리가 나올때까지 걸리는 딜레이 시간을 지루하게 느낄 수 있도록 할 수 있지 않을까? 라는 생각이 드네요 !!

2022-11-06 07:07 UTC, mxnxxii commented on WeHere/Views&ViewModels/Components/Pin/PinView.swift
> +struct PinView: View {
제 생각은 두개의 중간이 가장 좋을 것 같은데 ,, 어렵겠죠? ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
지도를 줄였을 때, 핀의 크기가 크다고 느껴지기도 하고 주위에 핀이 많이 꽂혔을 때 핀의 크기가 시야를 방해한다는 생각이 들어서 지금보다는 조금 더 작은 크기가 좋은 것 같아요 !!

[지도 줄였을 때]
![IMG_9594](https://user-images.githubusercontent.com/103024869/200158646-0a1e8253-0966-42c9-b902-ad4788b5095b.png)

2022-11-06 07:29 UTC, phainestha1 commented on WeHere/Views&ViewModels/Map/MapViewModel.swift
> +            mapRegion = MKCoordinateRegion(center: locationManager.location!.coordinate,
언래핑 있네요..! 괜찮은걸까요?

2022-11-06 07:30 UTC, phainestha1 commented on WeHere/Views&ViewModels/Components/Pin/PinView.swift
> +struct PinView: View {
이미지가 아닌 직접 만든 모양을 사용해서 재사용성 높이는 것으로 로미와 논의하였습니다.
개발자분들의 건강과 안위가 최고입니다.

브리 확인하신 후 코멘트 종료 부탁드리겠습니다.

2022-11-06 07:35 UTC, phainestha1 commented on WeHere/Views&ViewModels/Map/MapView.swift
> +                                HapticManager.instance.notification(type: .success)
이렇게 하고 싶으시답니다.

https://user-images.githubusercontent.com/88080251/200159382-56a87b4c-93a3-4105-9fa8-f44780efefb9.mp4

```swift
Image("ic-cafe-circle", label: Text("Cafe Pins"))
// .delay(0.5) 없이 바로 애니메이션이 작동하는 것으로 부탁드립니다.
  .animation(.easeInOut(duration: 0.5), value: showFabAnimation)

Button {
  self.showFabAnimation.toggle()
  // 딜레이 없이 햅틱을 추가합니다.
  HapticManager.instance.notification(type: .success) 
} label: {
    HeartView()
      .frame(width: 92, height: 92)
}
  .buttonStyle(SampleButtonStyle())

struct SampleButtonStyle: ButtonStyle {
  func makeBody(configuration: Self.Configuration) -> some View {
    configuration.label
          .scaleEffect(configuration.isPressed ? 1.1 : 1)
      .background(.clear)
  }
}
```

2022-11-06 09:42 UTC, chaneeii commented on WeHere/Views&ViewModels/Map/MapView.swift
> +                                HapticManager.instance.notification(type: .success)
네넹 
제 댓글 바로 위 버전으로 적용할게요!

요거말고도
애니메이션이나 디자인 중 피그마로 표현이 안되는 부분은 사실 제가 감으로 해야하다보니 어렵네요 ㅎㅎ
자세하게 작성해주시면 제가 그 방향대로 최대한 구현시켜두겠습니다~!

2022-11-06 09:43 UTC, chaneeii commented on WeHere/Views&ViewModels/Map/MapViewModel.swift
> +            mapRegion = MKCoordinateRegion(center: locationManager.location!.coordinate,
네네 이 코드 자체가 위에서 locationManager를 이미 할당받은 
그니깐 이미 locationManager 자체가 확보된 상태이기 때문에 문제없을 것 같습니다..!

2022-11-06 09:45 UTC, chaneeii commented on WeHere/Views&ViewModels/Components/Pin/PinView.swift
> +struct PinView: View {
그럼 커스텀 핀 + 작은사이즈로 해두도록 하겠습니다..! 

혹시 나중에라도 핀사이즈를 바꾸고 싶은 경우 컴포넌트를 이미 재사용성을 극대화 시켜둬서 이 PR 이 닫혀도 수정이 가능합니다 
핀 사이즈 조절자체는 어렵지 않으니 피그마로 원하는 핀사이즈 알려주시면 그거 맞춰서 반영할게요..!

2022-11-06 12:59 UTC, chaneeii commented on WeHere/Views&ViewModels/Map/MapView.swift
> +                                HapticManager.instance.notification(type: .success)
반영
ecdaeae7811b5a07707a8906d1cc2402ae1c925a

2022-11-06 12:59 UTC, chaneeii commented on WeHere/Views&ViewModels/Components/Pin/PinView.swift
> +struct PinView: View {
반영!
248cb5c70209b64431e0b52e391eabf54910fca5

2022-11-07 04:01 UTC, phainestha1 approved these changes
😇

2022-11-09 03:25 UTC, E-know requested changes
[P3] 샘플 이미지가 저작권에 위배되는지 궁금합니다.

2022-11-09 03:25 UTC, E-know commented on WeHere/Managers/HapticManager.swift
> +    static let instance = HapticManager()
[P1] 애플 공식 홈페이지 예시코드에서 싱글톤은 shared로 사용하고 있습니다. 맞춰가는 것이 어떨까요?

2022-11-09 03:25 UTC, E-know commented on WeHere/Managers/HapticManager.swift
> +}
[P1] 싱글톤 구현을 생각하신게 맞을까요? 생성자가 private 걸려있지 않은것 같습니다.

2022-11-09 03:25 UTC, E-know commented on WeHere/Views&ViewModels/Map/MapView.swift
> +    @EnvironmentObject private var viewModel: MapViewModel
[P1] EnvironmentObject 선언을 사용과 동시에 Map 하위 View 에게 파라미터로 넘겨시는 이유가 궁금합니다!😃

2022-11-09 03:25 UTC, E-know commented on WeHere/Views&ViewModels/Map/MapView.swift
> +}
[P3] 이 부분은 분리하는게 어떨까요??

2022-11-09 04:55 UTC, E-know commented
[P5](PR내용)

> ✅ Components
> 공통으로 사용하는 컴포넌트가 있어 이부분을 우선 Views&ViewModels 쪽에 넣어두었는데
> 폴더위치가 애매하네요 🥹 한단계 위로 올릴까요?
구조변경에 합리적인 이유가 있다면 합당할 것 같습니다.

> 알수없는 보라 경고
> 요 에러를 해결하고 싶은데 왜 뜨는지 잘 모르겠네요 🥲
> 혹시 이것에 대해서 아는게 있을까요? @E-know
이 부분에 있어서 제가 아는 얇은 지식으로는 메인쓰레드가 아닌 곳에서 메인 쓰레드가 관리하는 메모리를 수정하고자 할 때 일어나는 것으로 알고 있습니다. 예를 들어서 메인쓰레드가 아닌 곳에서 Published를 재정의 하는 것들이요!
@MainActor를 사용해서 해결한 적이 있는데 한번 더 체크해보겠습니다!

2022-11-09 12:05 UTC, chaneeii commented
> [P5](PR%EB%82%B4%EC%9A%A9)
> 
> > ✅ Components
> > 공통으로 사용하는 컴포넌트가 있어 이부분을 우선 Views&ViewModels 쪽에 넣어두었는데
> > 폴더위치가 애매하네요 🥹 한단계 위로 올릴까요?
> 
> 구조변경에 합리적인 이유가 있다면 합당할 것 같습니다.

구조를 변경하기 보다 현재 Views 와 ViewModels로 폴더 네이밍이 되어있어
나머지는 기능별로 Components 만 컴포넌트인 상태가 약간 불편해서 그랬습니다..!


> > 알수없는 보라 경고
> > 요 에러를 해결하고 싶은데 왜 뜨는지 잘 모르겠네요 🥲
> > 혹시 이것에 대해서 아는게 있을까요? @E-know
> 
> 이 부분에 있어서 제가 아는 얇은 지식으로는 메인쓰레드가 아닌 곳에서 메인 쓰레드가 관리하는 메모리를 수정하고자 할 때 일어나는 것으로 알고 있습니다. 예를 들어서 메인쓰레드가 아닌 곳에서 Published를 재정의 하는 것들이요! @mainactor를 사용해서 해결한 적이 있는데 한번 더 체크해보겠습니다!

메인스레드에 돌리는 방법 몇가지로는 해결이 안되더라구요 한번 방법을 고민해보겠습니다
코드는 잘못없겟죠,,, 아마 저의 잘못 (인데 버전 몇 이후로 발생하는 이슈같아요(

2022-11-09 12:12 UTC, chaneeii commented on WeHere/Managers/HapticManager.swift
> +    static let instance = HapticManager()
무지성 복붙을 해두고 수정을 깜빡했네요 😂
하는 김에 메인스레드에서 햅틱가도록 같이 리팩토링 해두었습니다
2b19d77c64a60e6ac003eb52876152e7b48aa83f

2022-11-09 12:12 UTC, chaneeii commented on WeHere/Managers/HapticManager.swift
> +}
위와 동일합니다
2b19d77c64a60e6ac003eb52876152e7b48aa83f

2022-11-09 12:43 UTC, chaneeii commented on WeHere/Views&ViewModels/Map/MapView.swift
> +    @EnvironmentObject private var viewModel: MapViewModel
스유 너무 어렵네요
우선,, 저 Map을 스유에서 어떻게 잘 써야할지 몰라서 요렇게 하게 되었습니다 🥲

요 커멘트보고 EnvironmentObject 를 좀 다시 보고 스유 프로젝트를 좀 봤는데
제가 느끼기에 위치정보가 거의 모든 뷰에서 사용해서, EnvironmentObject 를 사용하면 좋겟다! 싶어 이렇게 작업했는데
단순히 MapViewModel 이 아니라 EnvironmentObject를 상태관리용으로 사용하는게 좀 더 효율적인것같기도 하고 
이게 맞나 싶기도 하네요 🥹

너무 오랜만의 스유라 되게 스위프트ui 를 잘쓰고 싶은데 어렵네요 ㅋ큐ㅠ 
더 좋은 방법이 있다면 추천해주세요

저는 아예 각잡고 state관리를 하는걸 하나 만들거나 우선 StateObject 로 바꿀까 고민중에 있습니다..!

2022-11-10 11:32 UTC, chaneeii commented
> [P3] 샘플 이미지가 저작권에 위배되는지 궁금합니다.

샘플이미지는 unsplash 에서 사용가능한걸로 가져와서 괜찮을 것 같습니다

2022-11-15 07:18 UTC, E-know commented
1. Viewmodel를 EnvironmentObject로 선언하신 이유가 있으실까요??
2. 보라색 경고는 알아본 결과 Published로 선언한 변수를 Binding으로 넘기고 Binding에서 변화가 생겼을 때에 Main Thread에서 변경이 이뤄졌다고 생각하지 않는 에러인 것 같습니다!

2022-11-18 09:39 UTC, E-know commented
보라색 에러만 해결하면 머지를~!~!

2022-11-19 14:06 UTC, E-know approved these changes

2022-11-19 14:06 UTC, merged