Feat/main/search
Team-WeHere/WeHere pull request #6
Opened 2022-11-07 19:06 UTC by E-know

## Description
 

- MapKit의 MKLocalSearch를 통해서 검색 후에 보여주는 View 구현
- 돋보기 누르면 검색창 나오는 Animation 구현

## Test Points

- App 에서 `MainView`를 호출 해주세요.

## References

- 시뮬레이터에서는 미국이 기본 값으로 설정되어있기에 한국으로 설정후 검색해주세요.

2022-11-08 12:01 UTC, phainestha1 commented on WeHere/Views&ViewModels/Main/Search/SearchView.swift
> +        ZStack {
ZStack 대신 아래 방법은 어떠세요? 들여쓰기를 한 번 줄일 수 있습니다
```swift
  TextField("검색어를 입력해주세요", text: $searchKeyword)
                .padding(.horizontal, 20)
                .foregroundColor(.black)
                .background(.white)
                .cornerRadius(20)
                .frame(width: UIScreen.main.bounds.width - 32)
                .onSubmit {  }
```

2022-11-08 15:15 UTC, chaneeii requested changes
몇가지 수정사항이 보이네요! 
확인부탁드릴게요~!~
검색기능 레퍼도 적을텐뎅,, 고생하셨습니다!

2022-11-08 15:15 UTC, chaneeii commented on WeHere/Views&ViewModels/Main/Search/SearchResultCell.swift
> +//}
혹은 swift 의 preview 는 release 코드에 사실 들어가서 좋을게 없어서 
저는 #if debug 로 처리해두기도 합니다..!

2022-11-08 15:15 UTC, chaneeii commented on WeHere/Views&ViewModels/Main/Search/SearchResultCell.swift
> +        else { return "표시할 수 없습니다."}
p2)
요걸 지금할지 나중에 할지 모르지만 타입(or 모델)을 하나 만들어서 관리하는게 좋을 것 같습니다

2022-11-08 15:15 UTC, chaneeii commented on WeHere/Views&ViewModels/Main/Search/SearchResultCell.swift
> +        else { return "표시할 수 없습니다."}
p1)
지금 뭔가 도로명 주소와 구주소가 혼재된 상태인것 같습니다!
이부분을 하나의 주소로 통일하는게 어떨까요?

<img width="352" alt="스크린샷 2022-11-09 오전 12 06 50" src="https://user-images.githubusercontent.com/63157395/200600524-e9f4e7f0-a439-4450-ba72-817823818cfe.png">


[경북 포항시 남구 중흥로 96](https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%EB%B2%84%EA%B1%B0%ED%82%B9+%EC%A4%91%ED%9D%A5%EB%A1%9C&oquery=%EB%B2%84%EA%B1%B0%ED%82%B9&tqi=h2pwCwp0J1Zss5cqaE0ssssstDo-240816#)[지도](https://map.naver.com/v5/entry/place/743556618?c=14399291.105938714%2C4302485.390552616%2C13%2C0%2C0%2C0%2Cdh&placePath=%2Fhome&entry=plt)

또한 예전에 다니던 회사에서 주소 사용시 저장하던 변수명이 직관적이여서 추천해보고 갑니다.
si/do
gu/gun
dong
road
~~

2022-11-08 15:15 UTC, chaneeii commented on WeHere/Views&ViewModels/Main/Search/SearchView.swift
> +            }
p3)
이부분이 애니메이션이 사라질때 늦게 사라져서 잔상이 남네요
현재는 배경이 회색이라 티가 안나는데 다른색으로 바꾸니 티가 나네요..! 
타이밍을 조절해야할것같아요!

2022-11-08 15:15 UTC, chaneeii commented on WeHere/Views&ViewModels/Main/Search/SearchView.swift
> +            }
https://user-images.githubusercontent.com/63157395/200601688-2552abc4-ab19-4b26-91c8-e42eb47bc70c.mp4

2022-11-08 15:15 UTC, chaneeii commented on WeHere/Views&ViewModels/Main/Search/SearchView.swift
> +            }
그리고 마지막에 덜덜 떨리네요...?@!ㅠ

2022-11-08 15:15 UTC, chaneeii commented on WeHere/Views&ViewModels/Main/Search/SearchView.swift
> +            customTextField
p3)
customTextField 가 여기저기서 사용될 수 있을 것 같은 이름이라 조금 더 정확하게 이 기능을 담은 작명이 필요해보입니다
searchTextField 는 어떨까요?

2022-11-08 15:18 UTC, chaneeii commented on WeHere/Assets.xcassets/Colors/Contents.json
> +}
or 제 branch 가 먼저 머지되면 rebase 후 작업을 진행해도 좋을 것 같습니다

2022-11-10 02:16 UTC, phainestha1 commented
커밋은 영문 작성으로 합의했습니다.
노션-개발-Conventions를 확인 부탁드립니다!

2022-11-18 08:57 UTC, E-know commented on WeHere/Views&ViewModels/Main/MainView.swift
> +import MapKit
그 이유는 import가 많아지면 찾기가 어렵다는 점입니다! 수정하겠습니다!

2022-11-18 08:58 UTC, E-know commented on WeHere/Views&ViewModels/Main/MainView.swift
> +        ZStack {
이 부분은 gray 대신에 Map이 오는 곳입니다. 제가 구분하기 위해서 gray를 넣었기에 ZStack이 좋을 것 같습니다.

2022-11-18 08:59 UTC, E-know commented on WeHere/Views&ViewModels/Main/MainView.swift
> +                    .padding(.horizontal, 16)
저는 숫자가 좋다고 생각합니다. 왜냐하면 각 패딩이 깨졌거나 수정을 해야 할 때에 enum으로 관리하게 된다면 수정해야하는 부분이 급작스럽게 늘어나게 됩니다.

2022-11-18 09:10 UTC, E-know commented on WeHere/Assets.xcassets/Colors/Contents.json
> +}
Color Asset 코드가 적용되고난 후에 제가 다시 수정하는 방향으로 진행하겠습니다.

2022-11-18 09:11 UTC, E-know commented on WeHere/Extentions/File.swift
> +//
가끔 빈 폴더를 깃허브에서 인식하지 못하는 버그가 있어서 임시로 만들어 놓았습니다. 삭제하겠습니다.

2022-11-18 09:12 UTC, E-know commented on WeHere/Extentions/Font+.swift
> +}
원래라기 보다는 전 혹시 모르는 오류를 방지하고자 적는 편이긴 합니다.

2022-11-18 09:12 UTC, E-know commented on WeHere/Views&ViewModels/Main/Search/SearchResultCell.swift
> +//}
오 #if debug 키워드 첨 알아갑니다. 줍줍!

2022-11-18 09:14 UTC, E-know commented on WeHere/Views&ViewModels/Main/Search/SearchResultCell.swift
> +        else { return "표시할 수 없습니다."}
1. 위와 같은 경우는 도로명주소와 구주소를 혼용해서 데이터를 던져줘서 이부분은 추후에 구주소를 도로명주소로 수정하는 API를 찾아보겠습니다.
2. 오 스위프트에서 변수명에 / 는 안되므로 /를 제외하고는 수정하겠습니다 좋을 것 같습니다.

2022-11-18 09:16 UTC, E-know commented on WeHere/Views&ViewModels/Main/Search/SearchView.swift
> +            customTextField
변수명 이름 수정하겠습니다!

2022-11-18 09:22 UTC, E-know commented on WeHere/Views&ViewModels/Main/Search/SearchView.swift
> +            }
수정했습니다!

2022-11-18 09:38 UTC, E-know commented
@chaneeii 코드리뷰 완료했습니다!

2022-11-19 06:37 UTC, phainestha1 approved these changes

2022-11-19 11:42 UTC, chaneeii commented on WeHere/Views&ViewModels/Main/Search/SearchResultCell.swift
> +        else { return "표시할 수 없습니다."}
아하 / 는 구분상 두었는데 역시 알아서 잘 처리 감사합니다 !

2022-11-19 11:44 UTC, chaneeii approved these changes

2022-11-19 15:50 UTC, merged